"""The trusted Shell — a local, dependency-free web UI over the loopback API (Phase 9).

``decima.shell`` is the daily-driver frontend. It is TRUSTED application code: the HTML/
CSS/JS under ``frontend/`` is shipped by us, never generated by an agent at runtime, and
is served to the browser from one local origin by ``serve.py``. The Shell reaches every
effect through the existing backend API (``decima.services.api``) — it writes no storage,
mints no authority, and bypasses no command. All model-generated and imported content is
rendered as escaped TEXT, never as markup, and human approval actions live only in the
trusted approval-inbox component (handoff §9, invariant 5).
"""

from __future__ import annotations

__all__ = ["serve"]
